### ISSUE TITLE
Request: Need a Single Java-8 Util in place of separate projects like Stream Utils and Collectors Util.

### ISSUE THREAD

**Issue by loganathan001** [JosePaumard/streams-utils#6]
Hi Jose Paumard,
This is just a request.
Having your two useful projects such as Stream Utils and Collectors Util in git, it seems if we need the two libraries we should download two separate dependencies. But my opinion is they can co-exist in single library called something like 'Java8-utils' in which you can add any other new utility related to Java8. Also it will be useful to have a single library instead of downloading multiple dependencies.

Inspired by your Java8 tutorial, I am also added a few utility methods in my Java-Utils git project  (at https://github.com/loganathan001/Java-Utils) such as flattening Stream of Optionals, flattening Optional of Optionals and Mappable version of Primitive type optionals, which I would like to add as my contribution to the single Java8-library if you create one. Please validate if they are useful to add to your library. Also please let me know if it is good idea to have such single library as I request.

Thanks & Regards,
Loganathan.S

**Comment by JosePaumard** [comment]
Hello, 

In fact you dont: CollectorsUtils depends on StreamsUtils, so if you pull this one, you will have them both. Which might be an issue since moving the version of StreamsUtils will require moving the version of CollectorsUtils also, for compatibility reasons... 

As for yout work on Optionals. I do not think that encouraging Optional<Optional> and Stream<Optional> through such an API is such a great idea. You might be interested in this talk by Stuart Marks: https://www.youtube.com/watch?v=Ej0sss6cq14 in which reasons for that are given. 

Thanks & regards, 

José

**Comment by loganathan001** [comment]
Thank you Jose Paumard for your reply! And thanks for your reference video on Optionals, and I will get my understanding with it.
