### ISSUE TITLE
Failing tests using the TryAdvanceCheckingSpliterator

### ISSUE THREAD

**Issue by blalasaadri** [JosePaumard/streams-utils#9]
On the current master (HEAD is commit fc6292b), 13 of 217 unit tests are failing, all of them seemingly related to the `TryAdvanceCheckingSpliterator`. Something there seems to be broken.

**Comment by JosePaumard** [comment]
First of all: thank you for your report!

These tests, as is, are failing with Java 9, which is not supported by v1.7 of Streams Utils. I will publish a 2.0 version soon, with Java 9 support and in which those issues are fixed. It still needs some polishing.

**Comment by blalasaadri** [comment]
From what I can see, the error with Java 9 is due to the implementation of `ReferencePipeline#count` now calling the `Spliterator#estimateSize` method, which doesn't always return the best possible estimation right now. I've created pull request https://github.com/JosePaumard/streams-utils/pull/13 with some suggested fixes for that; maybe that will help? For me, the tests work with both Java 8 and 9 now.

**Comment by JosePaumard** [comment]
Thank you for your contribution! It's now fixed in 2.0. 
I think there are issues in it though. Since a cross product of N values cannot return more than N*N values, I doubt it could return a factorial(N), even divided by 2 ;)
BTW, and this is also true for your other PR: dividing your PRs in small commits makes possible to partially accept them, by cherry picking.
